export const db =  [
    {
      id: 1,
      productName: "Wireless Noise Cancelling Headphones",
      imgSrc: "/images/products/headphones.jpg",
      imgAlt: "Noise Cancelling Headphones",
      soldBy: "SoundPro Inc.",
      inStock: true,
      price: 199.99,
      originalPrice: 249.99,
      count: 2,
      rating: 4.5,
    },
    {
      id: 2,
      productName: "Smart Fitness Watch",
      imgSrc: "/images/products/watch.jpg",
      imgAlt: "Smart Fitness Watch",
      soldBy: "FitGadget Store",
      inStock: false,
      price: 149.99,
      originalPrice: null,
      count: 1,
      rating: 4.0,
    },
    {
      id: 3,
      productName: "4K Ultra HD TV",
      imgSrc: "/images/products/tv.jpg",
      imgAlt: "Ultra HD TV",
      soldBy: "Vision Electronics",
      inStock: true,
      price: 799.99,
      originalPrice: 899.99,
      count: 1,
      rating: 4.8,
    },
  ]
